"""Robust derivative fitting and 6-DOF PMM matrix assembly."""

from __future__ import annotations

import math
from typing import Any, Mapping, Sequence

import numpy as np

from .pmm_common import *
from .pmm_config import SixDofConfig, TrialPlan, _require_mapping
from .pmm_kinematics import r2_score
from .pmm_trials import SixDofTrial, build_trial, project_trial_harmonics, residualize_trial


def robust_fit(
    X: np.ndarray,
    y: np.ndarray,
    max_iter: int = 30,
    *,
    huber_k: float = 1.5,
) -> np.ndarray:
    """Huber IRLS with an explicit, reproducible tuning constant."""

    if not math.isfinite(huber_k) or huber_k <= 0.0:
        raise ValueError("huber_k must be finite and positive")
    beta = np.linalg.lstsq(X, y, rcond=None)[0]
    for _ in range(max_iter):
        residual = y - X @ beta
        median = float(np.median(residual))
        scale = 1.4826 * float(np.median(np.abs(residual - median)))
        if scale <= 1e-15:
            break
        cutoff = huber_k * scale
        weights = np.ones_like(residual)
        large = np.abs(residual) > cutoff
        weights[large] = cutoff / np.abs(residual[large])
        root_weights = np.sqrt(weights)
        updated = np.linalg.lstsq(X * root_weights[:, None], y * root_weights, rcond=None)[0]
        if np.linalg.norm(updated - beta) <= 1e-10 * (1.0 + np.linalg.norm(beta)):
            beta = updated
            break
        beta = updated
    return beta


def _stack(
    trials: Sequence[SixDofTrial],
    harmonics: Sequence[int] | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    if not trials:
        raise ValueError("cannot fit an empty trial list")
    pairs = [
        residualize_trial(trial)
        if harmonics is None
        else project_trial_harmonics(trial, harmonics)
        for trial in trials
    ]
    return np.vstack([item[0] for item in pairs]), np.concatenate([item[1] for item in pairs])


def mount_sign_invariant_coefficients(X: np.ndarray, y: np.ndarray, sign: float) -> np.ndarray:
    """Return the diagonal fit after a rolled-mount sign transformation."""
    if sign not in (-1.0, 1.0):
        raise ValueError("mount sign must be -1 or +1")
    return robust_fit(sign * np.asarray(X), sign * np.asarray(y))


def fit_dof(
    trials: Sequence[SixDofTrial],
    config: SixDofConfig,
) -> dict[str, Any]:
    """Fit one diagonal channel for one nominal frequency."""

    harmonics = [int(value) for value in config.fit["load_harmonics"]]
    X, y = _stack(trials, harmonics)
    huber_k = float(config.fit["huber_k"])
    beta = robust_fit(X, y, huber_k=huber_k)
    prediction = X @ beta
    return {
        "beta": beta,
        "full_r2": r2_score(y, prediction),
        "fit_domain": "per_trial_harmonic_coefficients",
        "harmonics": harmonics,
        "condition": float(np.linalg.cond(X / np.maximum(np.std(X, axis=0), 1e-15))),
        "X": X,
        "y": y,
        "prediction": prediction,
    }


def _frequency_key(value: float) -> float:
    """Return a stable key for nominal frequencies generated by multiplication."""

    return round(float(value), 10)


def fit_by_frequency(
    trials_by_dof: Mapping[str, Sequence[SixDofTrial]],
    config: SixDofConfig,
) -> dict[tuple[str, float], dict[str, Any]]:
    """Fit repeats together while keeping every nominal frequency independent."""

    results: dict[tuple[str, float], dict[str, Any]] = {}
    minimum = int(config.quality["minimum_repeats_per_frequency"])
    for dof in DOFS:
        grouped: dict[float, list[SixDofTrial]] = {}
        for trial in trials_by_dof[dof]:
            grouped.setdefault(_frequency_key(trial.plan.nominal_frequency_hz), []).append(trial)
        for nominal_frequency_hz, trials in sorted(grouped.items()):
            if len(trials) < minimum:
                raise ValueError(
                    f"{dof} nominal frequency {nominal_frequency_hz:g} Hz has "
                    f"{len(trials)} trials; requires {minimum}"
                )
            result = fit_dof(trials, config)
            estimated = np.asarray([trial.frequency_hz for trial in trials], dtype=float)
            result.update(
                {
                    "dof": dof,
                    "trials": trials,
                    "nominal_frequency_hz": nominal_frequency_hz,
                    "mean_estimated_frequency_hz": float(np.mean(estimated)),
                    "min_estimated_frequency_hz": float(np.min(estimated)),
                    "max_estimated_frequency_hz": float(np.max(estimated)),
                    "estimated_frequency_std_hz": float(np.std(estimated)),
                    "included_repeats": len(trials),
                }
            )
            results[(dof, nominal_frequency_hz)] = result
    return results


def coefficient_metadata(dof: str, config: SixDofConfig) -> tuple[list[str], list[str], np.ndarray]:
    if dof not in DOFS:
        raise ValueError(f"unknown DOF {dof!r}")
    response = DOF_RESPONSE[dof]
    variable = DOF_VARIABLE[dof]
    half_rho = 0.5 * float(config.model["fluid_density_kg_m3"])
    length = float(config.model["wet_length_m"])
    if dof in {"sway", "heave"}:
        units = ["kg/m", "kg/m", "kg"]
        divisors = np.asarray([half_rho * length**2, half_rho * length**2, half_rho * length**3])
    else:
        units = ["kg*m", "kg*m^2", "kg*m^2"]
        divisors = np.asarray([half_rho * length**4, half_rho * length**5, half_rho * length**5])
    return (
        [f"{response}_u{variable}", f"{response}_{variable}|{variable}|", f"{response}_{variable}dot"],
        units,
        divisors,
    )


def direct_term(dof: str) -> str:
    return f"{DOF_RESPONSE[dof]}_{DOF_VARIABLE[dof]}@Uref"


def direct_unit(dof: str) -> str:
    return "N*s/m" if dof in {"sway", "heave"} else "N*m*s"


def coefficient_rows(
    results: Mapping[tuple[str, float], Mapping[str, Any]],
    config: SixDofConfig,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for (dof, nominal_frequency_hz), result in sorted(
        results.items(), key=lambda item: (DOFS.index(item[0][0]), item[0][1])
    ):
        trials = list(result["trials"])
        u_ref = float(np.mean([np.mean(trial.u) for trial in trials]))
        names, units, divisors = coefficient_metadata(dof, config)
        beta = np.asarray(result["beta"])
        common = {
            "dof": dof,
            "experiment": dof,
            "response": DOF_RESPONSE[dof],
            "variable": DOF_VARIABLE[dof],
            "nominal_frequency_hz": f"{nominal_frequency_hz:.10g}",
            "mean_estimated_frequency_hz": f"{float(result['mean_estimated_frequency_hz']):.10g}",
            "min_estimated_frequency_hz": f"{float(result['min_estimated_frequency_hz']):.10g}",
            "max_estimated_frequency_hz": f"{float(result['max_estimated_frequency_hz']):.10g}",
            "included_repeats": int(result["included_repeats"]),
            "reference_speed_m_s": f"{u_ref:.10g}",
            "full_r2": f"{float(result['full_r2']):.7g}",
            "fit_quality_flag": (
                "low_load_fit_r2"
                if float(result["full_r2"])
                < float(config.quality["minimum_load_fit_r2_for_flag"])
                else "ok"
            ),
            "standardized_condition_number": f"{float(result['condition']):.7g}",
        }
        for index, (name, unit) in enumerate(zip(names, units)):
            rows.append(
                {
                    **common,
                    "term": name,
                    "coefficient": f"{beta[index]:.10g}",
                    "unit": unit,
                    "nondimensional": f"{beta[index] / divisors[index]:.10g}",
                    "assumption_status": "0.562 m PMM scale; independent nominal-frequency fit; PLA wet rigid mass uses +15% CAD density correction then +2.5% water uptake; free water excluded; full sensor reaction wrench negated; timing and wrench origin remain systematic assumptions",
                }
            )
        rows.append(
            {
                **common,
                "term": direct_term(dof),
                "coefficient": f"{beta[0] * u_ref:.10g}",
                "unit": direct_unit(dof),
                "nondimensional": "",
                "assumption_status": "signed C1*Uref derivative at measured tow speed",
            }
        )
    return rows


def build_six_dof_diagonal(
    coefficient_rows_for_frequency: Sequence[Mapping[str, Any]],
    identification_metadata: Mapping[str, Any] | None = None,
    completion: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    selected_rows: dict[tuple[str, str], Mapping[str, Any]] = {}
    for row in coefficient_rows_for_frequency:
        key = (str(row["dof"]), str(row["term"]))
        if key in selected_rows:
            raise ValueError(f"duplicate coefficient row for {key}")
        selected_rows[key] = row
    added: list[float | None] = [None] * 6
    linear: list[float | None] = [None] * 6
    quadratic: list[float | None] = [None] * 6
    speeds: dict[str, float] = {}
    compact: dict[str, dict[str, float | str]] = {}
    for dof in DOFS:
        response = DOF_RESPONSE[dof]
        variable = DOF_VARIABLE[dof]
        names = [
            f"{response}_u{variable}",
            f"{response}_{variable}|{variable}|",
            f"{response}_{variable}dot",
        ]
        try:
            values = [-float(selected_rows[(dof, name)]["coefficient"]) for name in names]
            direct = selected_rows[(dof, direct_term(dof))]
        except KeyError as error:
            raise ValueError(f"missing coefficient row {error.args[0]}") from error
        index = DOF_INDEX[dof]
        added[index] = values[2]
        linear[index] = -float(direct["coefficient"])
        quadratic[index] = values[1]
        speed = float(direct.get("reference_speed_m_s", 0.0))
        speeds[variable] = speed
        compact[variable] = {
            "dof": dof,
            "response": response,
            "added_mass": added[index],
            "linear_damping_at_reference_speed": linear[index],
            "quadratic_damping": quadratic[index],
            "reference_speed_m_s": speed,
        }
    source_by_dof = ["unassigned", "PMM_experiment", "PMM_experiment", "unassigned", "PMM_experiment", "PMM_experiment"]
    if completion is not None:
        for index, name in ((0, "surge_u"), (3, "roll_p")):
            values = _require_mapping(completion.get(name), f"full_6d_completion.{name}")
            added[index] = float(values["added_mass"])
            linear[index] = float(values["linear_damping"])
            quadratic[index] = float(values["quadratic_damping"])
            source_by_dof[index] = "external_literature_prior"

    def matrix(diagonal: Sequence[float | None]) -> list[list[float | None]]:
        return [
            [diagonal[row] if row == column else 0.0 for column in range(6)]
            for row in range(6)
        ]

    return {
        "schema_version": 1,
        "result_scope": "one_nominal_frequency_complete_6x6_diagonal_hybrid_model_in_FLU_COM",
        "result_scale": "physical_0p562_m_PMM_towing_model",
        "frame": "FLU body axes at PMM towing-model COM: x forward, y left, z up",
        "row_order": list(ROW_ORDER),
        "column_order": list(COLUMN_ORDER),
        "experimentally_identified_mask": [False, True, True, False, True, True],
        "complete_diagonal_mask": [value is not None for value in added],
        "diagonal_source_by_dof": source_by_dof,
        "vertical_mapping": "explicit_FLU_R_HB_Rx_plus_90_about_forward_axis_after_full_sensor_reaction_wrench_negation",
        "fossen_definition": "tau_h=-M_A*nu_dot-D_L*nu-D_Q*(abs(nu)*nu)",
        "added_mass": matrix(added),
        "linear_damping_effective_at_reference_speed": matrix(linear),
        "quadratic_damping": matrix(quadratic),
        "diagonal_vectors": {
            "added_mass": added,
            "linear_damping_effective_at_reference_speed": linear,
            "quadratic_damping": quadratic,
        },
        "identified_by_velocity": compact,
        "reference_speed_m_s_by_velocity": speeds,
        "source_assumptions": dict(identification_metadata or {}),
        "physicality_warning": (
            "Signs are preserved from the source fit. Negative damping or added mass is reported "
            "without projection and remains provisional under timing and mount assumptions."
        ),
    }


def build_frequency_resolved_matrices(
    rows: Sequence[Mapping[str, Any]],
    identification_metadata: Mapping[str, Any],
    config: SixDofConfig,
) -> dict[str, Any]:
    """Build one model-scale diagonal matrix for each nominal PMM frequency."""

    frequencies = sorted({_frequency_key(float(row["nominal_frequency_hz"])) for row in rows})
    models: list[dict[str, Any]] = []
    for frequency in frequencies:
        selected = [
            row
            for row in rows
            if math.isclose(
                _frequency_key(float(row["nominal_frequency_hz"])),
                frequency,
                rel_tol=0.0,
                abs_tol=1.0e-12,
            )
        ]
        model = build_six_dof_diagonal(
            selected,
            identification_metadata,
            config.full_6d_completion,
        )
        model["nominal_frequency_hz"] = frequency
        model["mean_estimated_frequency_hz_by_dof"] = {
            dof: float(
                next(row for row in selected if row["dof"] == dof)[
                    "mean_estimated_frequency_hz"
                ]
            )
            for dof in DOFS
        }
        models.append(model)
    return {
        "schema_version": 1,
        "result_scope": "frequency_resolved_complete_6x6_diagonal_hybrid_models",
        "result_scale": {
            "wet_length_m": float(config.model["wet_length_m"]),
            "geometry_scale_of_real_robot": float(config.model["geometry_scale_of_real_robot"]),
            "PMM_and_CFD_length_ratio": 1.0,
            "coefficient_scale_factor_applied": 1.0,
            "full_scale_conversion_performed": False,
        },
        "nominal_frequencies_hz": frequencies,
        "models": models,
    }


def _timing_fit_rows(
    plans: Sequence[TrialPlan], config: SixDofConfig
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for shift in sorted({float(item) for item in config.timing["sensitivity_shifts_ms"]}):
        for dof in DOFS:
            built = [build_trial(plan, config, shift_ms=shift) for plan in plans if plan.dof == dof]
            frequencies = sorted({_frequency_key(trial.plan.nominal_frequency_hz) for trial in built})
            for frequency in frequencies:
                trials = [
                    trial
                    for trial in built
                    if _frequency_key(trial.plan.nominal_frequency_hz) == frequency
                ]
                result = fit_dof(trials, config)
                names, _, _ = coefficient_metadata(dof, config)
                mean_estimated = float(np.mean([trial.frequency_hz for trial in trials]))
                for name, value in zip(names, result["beta"]):
                    rows.append(
                        {
                            "sensor_time_shift_ms": f"{shift:.10g}",
                            "timing_group": DOF_TIMING_GROUP[dof],
                            "dof": dof,
                            "nominal_frequency_hz": f"{frequency:.10g}",
                            "mean_estimated_frequency_hz": f"{mean_estimated:.10g}",
                            "term": name,
                            "coefficient": f"{value:.10g}",
                            "full_r2": f"{float(result['full_r2']):.10g}",
                        }
                    )
    return rows
